import 'hammerjs';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';

import {
	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule
	} from '@angular/material';

@NgModule({
  imports: [ BrowserModule,
    	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule,
	AppRoutingModule,
	NoopAnimationsModule
  ],
exports: [ BrowserModule,
    	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule
],
})
export class MaterialModule { }